version: 0.2

phases:
  install:
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - echo $AWS_USERNAME
      - echo $AWS_PASSWORD
  build:
    commands:
       - mvn clean install -Dmaven.test.skip=true 
